# Site settings
title: "Prerna Dewan"
email: "prerna.dewan94@gmail.com"
description: >-
  PhD student in Economics at the Indian Statistical Institute, Delhi Centre.
  Research interests: Economics of education, labour economics, development economics
baseurl: "" # Leave blank for user/organization site
url: "https://prerna-dewan.github.io"

# Author settings
author:
  name   : "Prerna Dewan"
  avatar : "profile.png"
  bio    : "PhD student in Economics | ISI Delhi"
  email  : "prerna.dewan94@gmail.com"
  github : prerna-dewan
  scholar: r2rFGO4AAAAJ&hl=en
  linkedin: your-linkedin-username
  twitter: PrernaDewan94

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
show_excerpts: true
paginate: 0

# Minimal menu
navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
    footer_links: false

# home
home:
  layout: home
  author_profile: true

# sass
sass:
  sass_dir: _sass

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

@import "custom";
