# Site settings
title: "Prerna Dewan"
description: "Economics PhD student at the Indian Statistical Institute, Delhi Centre."
url: "https://prerna-dewan.github.io" # main site URL
baseurl: "" # leave empty for user.github.io sites
repository: "prerna-dewan/prerna-dewan.github.io"

# Author info
author:
  name: "Prerna Dewan"
  avatar: "profile.png" # put your headshot in /images or root folder
  bio: "Economics PhD student at the Indian Statistical Institute, Delhi Centre."
  location: "New Delhi, India"
  email: "prerna.dewan94@gmail.com"
  github: "prerna-dewan"
  googlescholar: "https://scholar.google.com/citations?user=r2rFGO4AAAAJ&hl=en"
  twitter: "PrernaDewan94"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins — ONLY GitHub Pages supported ones
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Defaults — makes new pages/posts use correct layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

navigation:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/

