locale: "en-US"
site_theme: "default"
title: "Prerna Dewan"
title_separator: "-"
name: &name "Prerna Dewan"
description: &description "Economics PhD student at the Indian Statistical Institute, Delhi Centre."
url: "https://prerna-dewan.github.io"
baseurl: ""
repository: "prerna-dewan/prerna-dewan.github.io"

author:
  avatar: "profile.png"
  name: "Prerna Dewan"
  bio: "Economics PhD student at the Indian Statistical Institute, Delhi Centre."
  location: "New Delhi"
  employer: "Indian Statistical Institute, Delhi Centre"
  uri: "https://prerna-dewan.github.io"
  email: "prerna.dewan94@gmail.com"
  googlescholar: "https://scholar.google.com/citations?user=r2rFGO4AAAAJ&hl=en"
  github: "prerna-dewan"
  twitter: "PrernaDewan94"

# Optional: keep publication categories if you'll use them
publication_category:
  manuscripts:
    title: 'Journal Articles'

# Site settings
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"

# Markdown + plugins
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
